# Generated by Django 5.2.1 on 2025-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('blog', models.TextField(max_length=5000)),
                ('created_by', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('url_link', models.URLField()),
                ('url_title', models.TextField(max_length=100)),
            ],
        ),
    ]
