# Generated by Django 5.2.1 on 2025-05-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_audioinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioinfo',
            name='title',
            field=models.TextField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
