# Generated by Django 5.2.1 on 2025-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_audioinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url_link',
            field=models.CharField(max_length=200),
        ),
    ]
