# Generated by Django 5.2.1 on 2025-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
