# Generated by Django 5.2.1 on 2025-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='Not provided', max_length=20),
        ),
    ]
