# Generated by Django 5.2.1 on 2025-05-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_profile_bio_profile_created_at_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioInfo',
        ),
    ]
